<a href="https://colab.research.google.com/github/aysenaozcan/DA-Hardskills/blob/master/Da_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x=np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
x.reshape((1,3)) #row vector via reshape

array([[1, 2, 3]])

In [ ]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
x[np.newaxis,:] #row vector via newaxis

array([[1, 2, 3]])

In [ ]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
z=[99,99,99]
print(np.concatenate([x,y,z]))


[ 1  2  3  3  2  1 99 99 99]


In [ ]:
#oop
class Car():
  pass

In [ ]:
class Car():
  model="BMW"
  color="Siyah"
  cylinder=8
  count_of_door=2

In [ ]:
car_one=Car() #car1 structure produced by Car class

In [ ]:
type(car_one)

__main__.Car

In [ ]:
car_one.model

'BMW'

In [ ]:
car_one.color

'Siyah'

In [ ]:
car_one.cylinder

8

In [ ]:
car_one.count_of_door

2

In [ ]:
dir(car_one)  #show the class attirubutes

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'color',
 'count_of_door',
 'cylinder',
 'model']

In [ ]:
class Car():
  def __init__(self): #It is the initial structure that constructs the class.
    print("İnit fonksiyonu çağrıldı.")

In [ ]:
car_one=Car()

İnit fonksiyonu çağrıldı.


In [ ]:
class Car():
  def __init__(self, model, color, cylinder, count_of_door): #External parameters
    self.model=model  #External parameters are defined in class Car attiributes
    self.color=color
    self.cylinder=cylinder
    self.count_of_door=count_of_door
    print("İnit fonksiyonu çağrıldı.")

In [ ]:
car_one=Car("Ford","White",8,2)

İnit fonksiyonu çağrıldı.


In [ ]:
car_one.model

'Ford'

In [ ]:
car_one.cylinder

8

In [ ]:
car_one.count_of_door

2

In [ ]:
car_one.color

'White'

In [ ]:
car_one=Car("BMW","Black",4,4)
car_two=Car("Ford","White",8,2)

İnit fonksiyonu çağrıldı.
İnit fonksiyonu çağrıldı.


In [ ]:
class developer():
  def __init__(self,name,surname,tel,languages,salary):
    self.name=name
    self.surname=surname
    self.salary=salary
    self.languages=languages
    self.tel=tel
  def show_the_data(self):
    print(f"Name: {self.name}, Surname: {self.surname}, Tel: {self.tel}, Languages: {self.languages}, Salary: {self.salary}")
  def new_language(self,new_language):
    print("Dil ekleniyor.")
    self.languages.append(new_language)
  def raise_salary(self,raise_amount):
    print("Maaş artıyor.")
    self.salary+=raise_amount

In [ ]:
c=developer("Sena","Özcan",123,["phyton","C","Java"], 40000,)
c.name,c.surname,c.salary,c.languages,c.tel

('Sena', 'Özcan', 40000, ['phyton', 'C', 'Java'], 123)

In [ ]:
c.show_the_data()

Name: Sena, Surname: Özcan, Tel: 123, Languages: ['phyton', 'C', 'Java'], Salary: 40000


In [ ]:
dir(developer)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'new_language',
 'raise_salary',
 'show_the_data']

In [ ]:
c.new_language("Matlab")

Dil ekleniyor.


In [ ]:
c.raise_salary(5000)

Maaş artıyor.


In [ ]:
class Employee():
  def __init__(self,name,surname,salary):
    print("Employee sınıfının init fonksiyonu çağrıldı.")
    self.name=name
    self.surname=surname
    self.salary=salary
  def show_the_data(self):
    print(f"Name: {self.name}, Surname: {self.surname}, Salary: {self.salary}")
    print("Employee sınıfının bilgileri gösterildi.")
  def dep_change(self,new_dep):
    print("Employee sınıfının departmanı değiştirildi.")
    self.dep=new_dep


In [ ]:
class Manager(Employee): #inheritance
  def raise_salary(self,raise_amount):
    print("Maaş artıyor.")
    self.salary+=raise_amount

In [ ]:
Manager=Manager("Sena","Özcan",40000)

Employee sınıfının init fonksiyonu çağrıldı.


In [ ]:
Manager.show_the_data()

Name: Sena, Surname: Özcan, Salary: 40000
Employee sınıfının bilgileri gösterildi.


In [ ]:
Manager.dep_change("HR")

Employee sınıfının departmanı değiştirildi.


In [ ]:
dir(Manager)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'dep',
 'dep_change',
 'name',
 'raise_salary',
 'salary',
 'show_the_data',
 'surname']

In [ ]:
Manager.raise_salary(5000)

Maaş artıyor.


In [ ]:
class Employee():
  def __init__(self,name,surname,salary):
    print("Employee sınıfının init fonksiyonu çağrıldı.")
    self.name=name
    self.surname=surname
    self.salary=salary
  def show_the_data(self):
    print(f"Name: {self.name}, Surname: {self.surname}, Salary: {self.salary}")
    print("Employee sınıfının bilgileri gösterildi.")
  def dep_change(self,new_dep):
    print("Employee sınıfının departmanı değiştirildi.")
    self.dep=new_dep

In [ ]:
class Manager(Employee): #overriding
  def __init__(self,name, surname, salary, dep, number_of_emp):
    super().__init__(name, surname, salary) # Call parent's __init__
    self.dep=dep
    self.number_of_emp=number_of_emp
    print("Manager sınıfının init fonksiyonu çağrıldı.")
  def raise_salary(self,raise_amount):
    self.salary+=raise_amount
    print("Manager sınıfının init fonksiyonu çağrıldı.")

In [ ]:
class Manager(Employee):

    def __init__(self, name, surname, salary, dep, number_of_emp):
        super().__init__(name, surname, salary)

        print("Yonetici sınıfının initi çağırıldı.")
        self.dep = dep
        self.number_of_emp = number_of_emp

    def show_the_data(self):
        print("Calisan sınıfının bilgileri gosterildi.")
        print(f"Isim: {self.name}, Soyisim: {self.surname}, Maas: {self.salary}, Dep: {self.dep}, Kisi_Sayisi: {self.number_of_emp}")

    def raise_salary(self, raise_amount):
        print("Maaş arttı.")
        self.salary+=raise_amount

In [ ]:
a=Manager("Mustafa", "Yilmaz", 20000,"Arge",10)

Employee sınıfının init fonksiyonu çağrıldı.
Yonetici sınıfının initi çağırıldı.


In [ ]:
a.show_the_data()

Calisan sınıfının bilgileri gosterildi.
Isim: Mustafa, Soyisim: Yilmaz, Maas: 20000, Dep: Arge, Kisi_Sayisi: 10


In [ ]:
a.raise_salary(5000)
print("Maaş artıyor.")

Maaş arttı.
Maaş artıyor.


In [ ]:
k=Manager("Ali","Yılmaz", 100,"HhhR", 10)

Employee sınıfının init fonksiyonu çağrıldı.
Yonetici sınıfının initi çağırıldı.


In [ ]:
k.show_the_data()

Calisan sınıfının bilgileri gosterildi.
Isim: Ali, Soyisim: Yılmaz, Maas: 100, Dep: HhhR, Kisi_Sayisi: 10


In [ ]:
k.raise_salary(500)

Maaş arttı.
